import {
  encodeAbiParameters, keccak256, stringToHex, type Address, type Hex
} from "viem";

/**
 * The ticket-interval Merkle-sum tree committed by `SinjohRaffleRewards.commitRound`, and the
 * per-slot winning-index derivation.
 *
 * This must stay byte-identical to `sinjoh-raffle-rewards/test/RaffleTree.sol` and
 * `SinjohRaffleRewards.winningIndex`. A divergence produces roots no proof can satisfy, which
 * would surface only as every claim on a live raffle reverting. `test/raffle-tree.test.ts` pins
 * it against fixtures generated by the Solidity reference.
 *
 * A leaf's interval start is never stored: the contract derives it from the proof by summing
 * every left sibling. That is what makes the intervals a partition rather than a set of ranges
 * an attestor could overlap.
 */

const LEAF_DOMAIN = keccak256(stringToHex("SINJOH_RAFFLE_LEAF_V1"));
const NODE_DOMAIN = keccak256(stringToHex("SINJOH_RAFFLE_NODE_V1"));
const EMPTY_DOMAIN = keccak256(stringToHex("SINJOH_RAFFLE_EMPTY_V1"));
const SLOT_DOMAIN = keccak256(stringToHex("SINJOH_RAFFLE_SLOT_V1"));

export interface RaffleTreeParams {
  chainId: number;
  raffle: Address;
  roundId: bigint;
  snapshotBlock: bigint;
}

export interface TicketLeaf {
  holder: Address;
  tickets: bigint;
}

export interface RaffleProofElement {
  siblingHash: Hex;
  siblingSum: bigint;
  siblingIsLeft: boolean;
}

export interface BuiltRaffleLeaf extends TicketLeaf {
  offset: bigint;
  leafHash: Hex;
  proof: RaffleProofElement[];
}

export interface BuiltRaffleTree {
  root: Hex;
  rootSum: bigint;
  leaves: BuiltRaffleLeaf[];
}

export function raffleLeafHash(
  params: RaffleTreeParams, holder: Address, tickets: bigint
): Hex {
  return keccak256(encodeAbiParameters(
    [{ type: "bytes32" }, { type: "uint256" }, { type: "address" }, { type: "uint64" },
      { type: "uint64" }, { type: "address" }, { type: "uint256" }],
    [LEAF_DOMAIN, BigInt(params.chainId), params.raffle, params.roundId, params.snapshotBlock,
      holder, tickets]
  ));
}

export function raffleNodeHash(
  leftHash: Hex, leftSum: bigint, rightHash: Hex, rightSum: bigint
): Hex {
  return keccak256(encodeAbiParameters(
    [{ type: "bytes32" }, { type: "bytes32" }, { type: "uint256" }, { type: "bytes32" },
      { type: "uint256" }],
    [NODE_DOMAIN, leftHash, leftSum, rightHash, rightSum]
  ));
}

export function raffleEmptyLeafHash(roundId: bigint): Hex {
  return keccak256(encodeAbiParameters(
    [{ type: "bytes32" }, { type: "uint64" }], [EMPTY_DOMAIN, roundId]
  ));
}

/** Leaves must be sorted ascending by holder, unique, and carry nonzero tickets. */
export function buildRaffleTree(
  params: RaffleTreeParams, leaves: readonly TicketLeaf[]
): BuiltRaffleTree {
  if (leaves.length === 0) throw new Error("cannot build a tree with no eligible holders");
  let previous = "";
  for (const leaf of leaves) {
    const holder = leaf.holder.toLowerCase();
    if (leaf.tickets <= 0n) throw new Error(`leaf for ${leaf.holder} has no tickets`);
    if (holder <= previous) throw new Error("leaves must be sorted ascending and unique");
    previous = holder;
  }

  let width = 1;
  while (width < leaves.length) width *= 2;
  const padding = raffleEmptyLeafHash(params.roundId);

  const hashes: Hex[][] = [[]];
  const sums: bigint[][] = [[]];
  for (let i = 0; i < width; i++) {
    const leaf = leaves[i];
    hashes[0]!.push(leaf ? raffleLeafHash(params, leaf.holder, leaf.tickets) : padding);
    sums[0]!.push(leaf ? leaf.tickets : 0n);
  }

  let depth = 0;
  while (hashes[depth]!.length > 1) {
    const parentHashes: Hex[] = [];
    const parentSums: bigint[] = [];
    const level = hashes[depth]!;
    const levelSums = sums[depth]!;
    for (let i = 0; i < level.length; i += 2) {
      parentHashes.push(
        raffleNodeHash(level[i]!, levelSums[i]!, level[i + 1]!, levelSums[i + 1]!)
      );
      parentSums.push(levelSums[i]! + levelSums[i + 1]!);
    }
    hashes.push(parentHashes);
    sums.push(parentSums);
    depth += 1;
  }

  const built: BuiltRaffleLeaf[] = [];
  let offset = 0n;
  for (let i = 0; i < leaves.length; i++) {
    const leaf = leaves[i]!;
    const proof: RaffleProofElement[] = [];
    let index = i;
    for (let level = 0; level < depth; level++) {
      const sibling = index ^ 1;
      proof.push({
        siblingHash: hashes[level]![sibling]!,
        siblingSum: sums[level]![sibling]!,
        siblingIsLeft: sibling < index
      });
      index >>= 1;
    }
    built.push({ ...leaf, offset, leafHash: hashes[0]![i]!, proof });
    offset += leaf.tickets;
  }

  return { root: hashes[depth]![0]!, rootSum: sums[depth]![0]!, leaves: built };
}

/** Mirrors the contract's verification, including the derived interval start. */
export function verifyRaffleProof(
  leaf: BuiltRaffleLeaf, root: Hex, rootSum: bigint
): { valid: boolean; offset: bigint } {
  let hash = leaf.leafHash;
  let sum = leaf.tickets;
  let offset = 0n;
  for (const element of leaf.proof) {
    if (element.siblingIsLeft) {
      hash = raffleNodeHash(element.siblingHash, element.siblingSum, hash, sum);
      offset += element.siblingSum;
    } else {
      hash = raffleNodeHash(hash, sum, element.siblingHash, element.siblingSum);
    }
    sum += element.siblingSum;
  }
  const valid = hash === root && sum === rootSum;
  return { valid, offset: valid ? offset : 0n };
}

/** The leaf whose interval contains a winning index, or undefined if the index is out of range. */
export function ownerOfIndex(
  tree: BuiltRaffleTree, index: bigint
): BuiltRaffleLeaf | undefined {
  return tree.leaves.find(
    (leaf) => index >= leaf.offset && index < leaf.offset + leaf.tickets
  );
}

/**
 * The winning ticket index for one slot, matching `SinjohRaffleRewards.winningIndex`.
 *
 * Slots are independent draws from the same seed, so one holder may win more than one slot in a
 * round in proportion to its tickets.
 */
export function winningIndex(args: {
  chainId: number; raffle: Address; roundId: bigint; slot: number; seed: bigint;
  totalTickets: bigint;
}): bigint {
  if (args.totalTickets <= 0n) throw new Error("a round with no tickets has no winner");
  const digest = keccak256(encodeAbiParameters(
    [{ type: "bytes32" }, { type: "uint256" }, { type: "address" }, { type: "uint64" },
      { type: "uint8" }, { type: "uint256" }],
    [SLOT_DOMAIN, BigInt(args.chainId), args.raffle, args.roundId, args.slot, args.seed]
  ));
  return BigInt(digest) % args.totalTickets;
}
