import { encodeAbiParameters, keccak256, type Address, type Hex } from "viem";

/**
 * Canonical encoding and hash of an immutable raffle configuration.
 *
 * `SinjohRaffleRewardsFactory.predictRaffle(creator, salt, configHash)` is an on-chain view,
 * but calling it requires the `configHash` — `keccak256` of the canonical
 * `abi.encode(RaffleTypes.Config)`. This module produces that hash off-chain so a launch flow
 * can compute the raffle address in the same breath as the predicted curve. The encoding is
 * pinned byte-for-byte against a fixture generated by the raffle package's
 * `GenerateFixtures.t.sol`; any divergence between this tuple and the Solidity struct fails
 * the SDK suite before a flow can predict a wrong address.
 */

export interface RaffleStockReward {
  asset: Address;
  swapAdapter: Address;
  priceGuard: Address;
  routeData: Hex;
  guardData: Hex;
}

export const TicketBasis = { SNAPSHOT: 0, MIN_BALANCE: 1 } as const;

export interface RaffleConfig {
  creator: Address;
  attestor: Address;
  randomness: Address;
  prizeAsset: Address;
  protocolFeeRecipient: Address;
  taxRecipient: Address;
  tokensPerTicket: bigint;
  maxTicketsPerHolder: bigint;
  minPrize: bigint;
  maxPrize: bigint;
  prizeBps: number;
  recipientTaxBps: number;
  recycleTaxBps: number;
  minConfirmations: number;
  winnersPerRound: number;
  minRoundInterval: number;
  weightWindowBlocks: number;
  randomnessTimeout: number;
  claimWindow: number;
  /** 0 = SNAPSHOT, 1 = MIN_BALANCE (`TicketBasis`). */
  basis: number;
  /** Must be sorted ascending and unique; the raffle enforces it. */
  exclusions: Address[];
  stockRewards: RaffleStockReward[];
}

/** Mirrors `RaffleTypes.Config` exactly; order and widths are load-bearing. */
const CONFIG_COMPONENTS = [
  { name: "creator", type: "address" },
  { name: "attestor", type: "address" },
  { name: "randomness", type: "address" },
  { name: "prizeAsset", type: "address" },
  { name: "protocolFeeRecipient", type: "address" },
  { name: "taxRecipient", type: "address" },
  { name: "tokensPerTicket", type: "uint128" },
  { name: "maxTicketsPerHolder", type: "uint128" },
  { name: "minPrize", type: "uint128" },
  { name: "maxPrize", type: "uint128" },
  { name: "prizeBps", type: "uint16" },
  { name: "recipientTaxBps", type: "uint16" },
  { name: "recycleTaxBps", type: "uint16" },
  { name: "minConfirmations", type: "uint16" },
  { name: "winnersPerRound", type: "uint8" },
  { name: "minRoundInterval", type: "uint32" },
  { name: "weightWindowBlocks", type: "uint32" },
  { name: "randomnessTimeout", type: "uint32" },
  { name: "claimWindow", type: "uint32" },
  { name: "basis", type: "uint8" },
  { name: "exclusions", type: "address[]" },
  {
    name: "stockRewards",
    type: "tuple[]",
    components: [
      { name: "asset", type: "address" },
      { name: "swapAdapter", type: "address" },
      { name: "priceGuard", type: "address" },
      { name: "routeData", type: "bytes" },
      { name: "guardData", type: "bytes" }
    ]
  }
] as const;

/** Local-first validation; the raffle enforces the same rules on-chain. */
export function validateRaffleConfig(config: RaffleConfig): string[] {
  const issues: string[] = [];
  let previous = -1n;
  for (const exclusion of config.exclusions) {
    const numeric = BigInt(exclusion);
    if (numeric <= previous) {
      issues.push("exclusions must be sorted ascending by numeric address value and unique");
      break;
    }
    previous = numeric;
  }
  if (config.basis !== TicketBasis.SNAPSHOT && config.basis !== TicketBasis.MIN_BALANCE) {
    issues.push(`basis must be 0 (SNAPSHOT) or 1 (MIN_BALANCE), got ${config.basis}`);
  }
  return issues;
}

/** Canonical `abi.encode(config)` — a single struct argument, so one tuple. */
export function encodeRaffleConfig(config: RaffleConfig): Hex {
  const issues = validateRaffleConfig(config);
  if (issues.length > 0) throw new Error(`invalid raffle config: ${issues.join("; ")}`);
  return encodeAbiParameters(
    [{
      type: "tuple",
      components: CONFIG_COMPONENTS as unknown as { name: string; type: string }[]
    }],
    [config as unknown as Record<string, unknown>]
  );
}

/** The `configHash` the raffle factory derives its CREATE2 salt from. */
export function raffleConfigHash(config: RaffleConfig): Hex {
  return keccak256(encodeRaffleConfig(config));
}
