import { encodeAbiParameters, keccak256, type Address, type Hex } from "viem";

/**
 * Canonical encoding, validation, and hash of an immutable fee-router configuration.
 *
 * The encoded bytes — not a reformatted JSON object — are the configuration identity used
 * on-chain: `configHash` gates the router's CREATE2 address and every later readback. The
 * tuple below mirrors `RouterTypes.Config` exactly and is pinned byte-for-byte against a
 * fixture generated by the fee-router package's `GenerateRouterConfigFixture.t.sol`.
 *
 * Validation implements the router's documented hard limits so an invalid configuration
 * fails locally, with a readable reason, before any RPC call or signature.
 */

export const AssetKind = { NATIVE: 0, FIXED_ERC20: 1, SUBJECT: 2 } as const;

export interface AssetRef {
  /** 0 = NATIVE, 1 = FIXED_ERC20, 2 = SUBJECT (`AssetKind`). */
  kind: number;
  /** Must be zero for NATIVE and SUBJECT; the token address for FIXED_ERC20. */
  token: Address;
}

export interface Route {
  adapter: Address;
  routeData: Hex;
}

export interface Normalization {
  asset: AssetRef;
  route: Route;
  priceGuard: Address;
  maxAmountInPerCall: bigint;
}

export interface Allocation {
  destination: Address;
  bps: number;
  isSink: boolean;
  creatorMayRepoint: boolean;
  sinkConfig: Hex;
}

export interface Bucket {
  output: AssetRef;
  bps: number;
  route: Route;
  priceGuard: Address;
  maxAmountInPerCall: bigint;
  allocations: Allocation[];
}

export interface RouterConfig {
  creator: Address;
  protocolFeeRecipient: Address;
  weth: Address;
  /** Zero means only the creator may bind the subject. */
  launchpadAdapter: Address;
  normalizations: Normalization[];
  buckets: Bucket[];
}

/** Mirrors `RouterTypes.Config` exactly; order and widths are load-bearing. */
const CONFIG_COMPONENTS = [
  { name: "creator", type: "address" },
  { name: "protocolFeeRecipient", type: "address" },
  { name: "weth", type: "address" },
  { name: "launchpadAdapter", type: "address" },
  {
    name: "normalizations",
    type: "tuple[]",
    components: [
      {
        name: "asset",
        type: "tuple",
        components: [{ name: "kind", type: "uint8" }, { name: "token", type: "address" }]
      },
      {
        name: "route",
        type: "tuple",
        components: [{ name: "adapter", type: "address" }, { name: "routeData", type: "bytes" }]
      },
      { name: "priceGuard", type: "address" },
      { name: "maxAmountInPerCall", type: "uint128" }
    ]
  },
  {
    name: "buckets",
    type: "tuple[]",
    components: [
      {
        name: "output",
        type: "tuple",
        components: [{ name: "kind", type: "uint8" }, { name: "token", type: "address" }]
      },
      { name: "bps", type: "uint16" },
      {
        name: "route",
        type: "tuple",
        components: [{ name: "adapter", type: "address" }, { name: "routeData", type: "bytes" }]
      },
      { name: "priceGuard", type: "address" },
      { name: "maxAmountInPerCall", type: "uint128" },
      {
        name: "allocations",
        type: "tuple[]",
        components: [
          { name: "destination", type: "address" },
          { name: "bps", type: "uint16" },
          { name: "isSink", type: "bool" },
          { name: "creatorMayRepoint", type: "bool" },
          { name: "sinkConfig", type: "bytes" }
        ]
      }
    ]
  }
] as const;

const ZERO = "0x0000000000000000000000000000000000000000";
const MAX_BYTES = 1_024;
const MAX_ENCODED = 16_384;

function byteLength(data: Hex): number {
  return (data.length - 2) / 2;
}

function checkAssetRef(ref: AssetRef, label: string, issues: string[]): void {
  if (ref.kind === AssetKind.FIXED_ERC20) {
    if (ref.token === ZERO) issues.push(`${label}: FIXED_ERC20 requires a token address`);
  } else if (ref.kind === AssetKind.NATIVE || ref.kind === AssetKind.SUBJECT) {
    if (ref.token !== ZERO) issues.push(`${label}: kind ${ref.kind} requires a zero token`);
  } else {
    issues.push(`${label}: unknown asset kind ${ref.kind}`);
  }
}

/** The router's documented hard limits, checked locally before any RPC call. */
export function validateRouterConfig(config: RouterConfig): string[] {
  const issues: string[] = [];

  if (config.normalizations.length > 8) {
    issues.push(`at most 8 normalizations, got ${config.normalizations.length}`);
  }
  const seenAssets = new Set<string>();
  for (const [i, normalization] of config.normalizations.entries()) {
    const label = `normalizations[${i}]`;
    checkAssetRef(normalization.asset, `${label}.asset`, issues);
    const key = `${normalization.asset.kind}:${normalization.asset.token.toLowerCase()}`;
    if (seenAssets.has(key)) issues.push(`${label}: duplicate intake asset`);
    seenAssets.add(key);
    if (byteLength(normalization.route.routeData) > MAX_BYTES) {
      issues.push(`${label}.route.routeData exceeds ${MAX_BYTES} bytes`);
    }
  }

  if (config.buckets.length < 1 || config.buckets.length > 8) {
    issues.push(`buckets must number 1 to 8, got ${config.buckets.length}`);
  }
  let bucketBps = 0;
  for (const [i, bucket] of config.buckets.entries()) {
    const label = `buckets[${i}]`;
    bucketBps += bucket.bps;
    checkAssetRef(bucket.output, `${label}.output`, issues);
    if (byteLength(bucket.route.routeData) > MAX_BYTES) {
      issues.push(`${label}.route.routeData exceeds ${MAX_BYTES} bytes`);
    }
    if (bucket.allocations.length < 1 || bucket.allocations.length > 16) {
      issues.push(`${label} allocations must number 1 to 16, got ${bucket.allocations.length}`);
    }
    let allocationBps = 0;
    for (const [j, allocation] of bucket.allocations.entries()) {
      allocationBps += allocation.bps;
      if (byteLength(allocation.sinkConfig) > MAX_BYTES) {
        issues.push(`${label}.allocations[${j}].sinkConfig exceeds ${MAX_BYTES} bytes`);
      }
      if (!allocation.isSink && allocation.sinkConfig !== "0x") {
        issues.push(`${label}.allocations[${j}]: non-sink allocation carries sinkConfig`);
      }
    }
    if (bucket.allocations.length > 0 && allocationBps !== 10_000) {
      issues.push(`${label} allocation bps must total 10,000, got ${allocationBps}`);
    }
  }
  if (config.buckets.length > 0 && bucketBps !== 10_000) {
    issues.push(`bucket bps must total 10,000, got ${bucketBps}`);
  }

  return issues;
}

/** Canonical `abi.encode(config)` — a single struct argument, so one tuple. */
export function encodeRouterConfig(config: RouterConfig): Hex {
  const issues = validateRouterConfig(config);
  if (issues.length > 0) throw new Error(`invalid router config: ${issues.join("; ")}`);
  const encoded = encodeAbiParameters(
    [{
      type: "tuple",
      components: CONFIG_COMPONENTS as unknown as { name: string; type: string }[]
    }],
    [config as unknown as Record<string, unknown>]
  );
  if (byteLength(encoded) > MAX_ENCODED) {
    throw new Error(`encoded router config exceeds ${MAX_ENCODED} bytes`);
  }
  return encoded;
}

/** The `configHash` the router stores and the factory derives its CREATE2 salt from. */
export function routerConfigHash(config: RouterConfig): Hex {
  return keccak256(encodeRouterConfig(config));
}
