import {
  decodeAbiParameters, encodeAbiParameters, keccak256, type Address, type Hex
} from "viem";

/**
 * Canonical encoding, validation, and hash of the two sink configurations a router allocation
 * can carry. First funding freezes these bytes: the sink decodes them once, stores their hash,
 * and every later funding must present the identical encoding. Both codecs are pinned
 * byte-for-byte against fixtures generated by each package's `GenerateSinkConfigFixture.t.sol`.
 */

const ZERO = "0x0000000000000000000000000000000000000000";
const UINT16_MAX = 65_535;
const UINT24_MAX = 16_777_215;
const INT24_MIN = -8_388_608;
const INT24_MAX = 8_388_607;
const UINT48_MAX = 281_474_976_710_655;
const UINT128_MAX = (1n << 128n) - 1n;

function isZero(address: Address): boolean {
  return address.toLowerCase() === ZERO;
}

function checkUint(value: number, max: number, label: string, issues: string[]): void {
  if (!Number.isInteger(value) || value < 0 || value > max) {
    issues.push(`${label} must be an integer from 0 to ${max}`);
  }
}

function checkUint128(value: bigint, label: string, issues: string[]): void {
  if (value < 0n || value > UINT128_MAX) issues.push(`${label} must fit uint128`);
}

// ---------------------------------------------------------------------------
// Airdrop distributor: SinjohAirdropDistributor.Config
// ---------------------------------------------------------------------------

export interface AirdropSinkConfig {
  /** Raw asset units; must be greater than zero. */
  minPayout: bigint;
  /** 1 to 64. */
  maxBatchSize: number;
  /** 1 to 255 L2 blocks. */
  minConfirmations: number;
  /** At most 32 nonzero, unique addresses, sorted strictly ascending by numeric value. */
  exclusions: Address[];
}

const AIRDROP_COMPONENTS = [
  { name: "minPayout", type: "uint128" },
  { name: "maxBatchSize", type: "uint16" },
  { name: "minConfirmations", type: "uint16" },
  { name: "exclusions", type: "address[]" }
] as const;

export function validateAirdropSinkConfig(config: AirdropSinkConfig): string[] {
  const issues: string[] = [];
  checkUint128(config.minPayout, "minPayout", issues);
  checkUint(config.maxBatchSize, UINT16_MAX, "maxBatchSize", issues);
  checkUint(config.minConfirmations, UINT16_MAX, "minConfirmations", issues);
  if (config.minPayout <= 0n) issues.push("minPayout must be greater than zero");
  if (config.maxBatchSize < 1 || config.maxBatchSize > 64) {
    issues.push(`maxBatchSize must be 1 to 64, got ${config.maxBatchSize}`);
  }
  if (config.minConfirmations < 1 || config.minConfirmations > 255) {
    issues.push(`minConfirmations must be 1 to 255, got ${config.minConfirmations}`);
  }
  if (config.exclusions.length > 32) {
    issues.push(`at most 32 exclusions, got ${config.exclusions.length}`);
  }
  let previous = 0n;
  for (const exclusion of config.exclusions) {
    const numeric = BigInt(exclusion);
    if (numeric === 0n) {
      issues.push("exclusions must be nonzero");
      break;
    }
    if (numeric <= previous) {
      issues.push("exclusions must be strictly ascending by numeric address value");
      break;
    }
    previous = numeric;
  }
  return issues;
}

export function encodeAirdropSinkConfig(config: AirdropSinkConfig): Hex {
  const issues = validateAirdropSinkConfig(config);
  if (issues.length > 0) throw new Error(`invalid airdrop sink config: ${issues.join("; ")}`);
  return encodeAbiParameters(
    [{
      type: "tuple",
      components: AIRDROP_COMPONENTS as unknown as { name: string; type: string }[]
    }],
    [config as unknown as Record<string, unknown>]
  );
}

export function decodeAirdropSinkConfig(data: Hex): AirdropSinkConfig {
  const [decoded] = decodeAbiParameters(
    [{
      type: "tuple",
      components: AIRDROP_COMPONENTS as unknown as { name: string; type: string }[]
    }],
    data
  ) as unknown as [{
    minPayout: bigint; maxBatchSize: number; minConfirmations: number;
    exclusions: readonly Address[];
  }];
  return {
    minPayout: decoded.minPayout,
    maxBatchSize: decoded.maxBatchSize,
    minConfirmations: decoded.minConfirmations,
    exclusions: [...decoded.exclusions]
  };
}

export function airdropSinkConfigHash(config: AirdropSinkConfig): Hex {
  return keccak256(encodeAirdropSinkConfig(config));
}

// ---------------------------------------------------------------------------
// Liquidity manager: SinjohLiquidityManager.Config
// ---------------------------------------------------------------------------

export const Venue = { UNISWAP_V3: 0, UNISWAP_V4: 1 } as const;
export const FeeMode = { CREATOR: 0, TREASURY: 1, RECYCLE: 2, FUNDER: 3 } as const;

export interface LiquiditySinkConfig {
  /** 0 = UNISWAP_V3, 1 = UNISWAP_V4 (`Venue`). */
  venue: number;
  /** Must equal the asset supplied to `fund`. */
  quoteAsset: Address;
  poolFee: number;
  tickSpacing: number;
  /** Exact pool identity; must be zero for v3. */
  hooks: Address;
  swapAdapter: Address;
  priceGuard: Address;
  /** Nonempty, at most 1,024 bytes. */
  swapRouteData: Hex;
  /** 4,500 to 5,500. */
  quoteSwapBps: number;
  /** 0 to 500. */
  maxMintSlippageBps: number;
  minNotionalPerMint: bigint;
  maxNotionalPerMint: bigint;
  /** Seconds between successful mints. */
  minMintInterval: number;
  /** 0 = CREATOR, 1 = TREASURY, 2 = RECYCLE, 3 = FUNDER (`FeeMode`). */
  feeMode: number;
  /** Required nonzero for CREATOR and TREASURY modes. */
  feeRecipient: Address;
}

const LIQUIDITY_COMPONENTS = [
  { name: "venue", type: "uint8" },
  { name: "quoteAsset", type: "address" },
  { name: "poolFee", type: "uint24" },
  { name: "tickSpacing", type: "int24" },
  { name: "hooks", type: "address" },
  { name: "swapAdapter", type: "address" },
  { name: "priceGuard", type: "address" },
  { name: "swapRouteData", type: "bytes" },
  { name: "quoteSwapBps", type: "uint16" },
  { name: "maxMintSlippageBps", type: "uint16" },
  { name: "minNotionalPerMint", type: "uint128" },
  { name: "maxNotionalPerMint", type: "uint128" },
  { name: "minMintInterval", type: "uint48" },
  { name: "feeMode", type: "uint8" },
  { name: "feeRecipient", type: "address" }
] as const;

export function validateLiquiditySinkConfig(config: LiquiditySinkConfig): string[] {
  const issues: string[] = [];
  checkUint(config.venue, 255, "venue", issues);
  checkUint(config.poolFee, UINT24_MAX, "poolFee", issues);
  if (!Number.isInteger(config.tickSpacing)
    || config.tickSpacing < INT24_MIN || config.tickSpacing > INT24_MAX) {
    issues.push(`tickSpacing must be an integer from ${INT24_MIN} to ${INT24_MAX}`);
  }
  checkUint(config.quoteSwapBps, UINT16_MAX, "quoteSwapBps", issues);
  checkUint(config.maxMintSlippageBps, UINT16_MAX, "maxMintSlippageBps", issues);
  checkUint(config.minMintInterval, UINT48_MAX, "minMintInterval", issues);
  checkUint(config.feeMode, 255, "feeMode", issues);
  checkUint128(config.minNotionalPerMint, "minNotionalPerMint", issues);
  checkUint128(config.maxNotionalPerMint, "maxNotionalPerMint", issues);
  if (config.venue !== Venue.UNISWAP_V3 && config.venue !== Venue.UNISWAP_V4) {
    issues.push(`venue must be 0 (v3) or 1 (v4), got ${config.venue}`);
  }
  if (config.venue === Venue.UNISWAP_V3) {
    if (!isZero(config.hooks)) issues.push("v3 requires zero hooks");
    if (isZero(config.quoteAsset)) issues.push("v3 requires a nonzero quoteAsset");
  } else if (config.venue === Venue.UNISWAP_V4 && config.tickSpacing <= 0) {
    issues.push("v4 requires positive tickSpacing");
  }
  const routeBytes = (config.swapRouteData.length - 2) / 2;
  if (routeBytes < 1 || routeBytes > 1_024) {
    issues.push(`swapRouteData must be 1 to 1,024 bytes, got ${routeBytes}`);
  }
  if (config.quoteSwapBps < 4_500 || config.quoteSwapBps > 5_500) {
    issues.push(`quoteSwapBps must be 4,500 to 5,500, got ${config.quoteSwapBps}`);
  }
  if (config.maxMintSlippageBps > 500) {
    issues.push(`maxMintSlippageBps must be at most 500, got ${config.maxMintSlippageBps}`);
  }
  if (config.minNotionalPerMint <= 0n) issues.push("minNotionalPerMint must be greater than zero");
  if (config.maxNotionalPerMint < config.minNotionalPerMint) {
    issues.push("maxNotionalPerMint must be at least minNotionalPerMint");
  }
  if (config.feeMode < FeeMode.CREATOR || config.feeMode > FeeMode.FUNDER) {
    issues.push(`feeMode must be 0 to 3, got ${config.feeMode}`);
  }
  if ((config.feeMode === FeeMode.CREATOR || config.feeMode === FeeMode.TREASURY)
    && isZero(config.feeRecipient)) {
    issues.push("feeRecipient must be nonzero for CREATOR and TREASURY fee modes");
  }
  if (isZero(config.swapAdapter)) issues.push("swapAdapter must be nonzero");
  if (isZero(config.priceGuard)) issues.push("priceGuard must be nonzero");
  return issues;
}

export function encodeLiquiditySinkConfig(config: LiquiditySinkConfig): Hex {
  const issues = validateLiquiditySinkConfig(config);
  if (issues.length > 0) throw new Error(`invalid liquidity sink config: ${issues.join("; ")}`);
  return encodeAbiParameters(
    [{
      type: "tuple",
      components: LIQUIDITY_COMPONENTS as unknown as { name: string; type: string }[]
    }],
    [config as unknown as Record<string, unknown>]
  );
}

export function decodeLiquiditySinkConfig(data: Hex): LiquiditySinkConfig {
  const [decoded] = decodeAbiParameters(
    [{
      type: "tuple",
      components: LIQUIDITY_COMPONENTS as unknown as { name: string; type: string }[]
    }],
    data
  ) as unknown as [LiquiditySinkConfig];
  return { ...decoded };
}

export function liquiditySinkConfigHash(config: LiquiditySinkConfig): Hex {
  return keccak256(encodeLiquiditySinkConfig(config));
}
